import { it, expect } from "bun:test";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { CUSTOM_DEFAULT, appearanceColors, contrast, parseAppearance, colors } from "./appearance.ts";
import { sanitizeSettings, terminalTheme } from "./settings.ts";
it('bundled dark and light palettes preserve readable body contrast',()=>{for(const name of ['catppuccin','rose-pine'] as const)for(const mode of ['dark','light'] as const){const c=appearanceColors(name,mode,CUSTOM_DEFAULT)!;expect(contrast(c)).toBeGreaterThanOrEqual(4.5);expect(terminalTheme(mode,'amber',{appearancePreset:name,customColors:CUSTOM_DEFAULT}).background).toBe(c.surface);}});
it('rejects executable color data and unknown appearance import shapes',()=>{expect(colors({text:'url(https://evil)'}).text).toBe(CUSTOM_DEFAULT.text);expect(()=>parseAppearance('{"version":2}')).toThrow();expect(()=>parseAppearance('x'.repeat(16001))).toThrow();const settings=sanitizeSettings({appearancePreset:'catppuccin',uiFontFamily:'D2Coding'});expect(settings.appearancePreset).toBe('catppuccin');expect(sanitizeSettings({}).appearancePreset).toBe('default');});
it('appearance import whitelists fields rather than importing credentials',()=>{const result=parseAppearance(JSON.stringify({version:1,appearancePreset:'custom',customColors:CUSTOM_DEFAULT,theme:'dark',uiFontFamily:'',terminalFontFamily:'',chatFontFamily:'',token:'secret'}));expect(result).not.toHaveProperty('token');});
it('ships the exact font assets with original license notices',()=>{const root=new URL('../../public/appearance/',import.meta.url);const sources=JSON.parse(readFileSync(new URL('sources.json',root),'utf8'));expect(sources).toHaveLength(8);for(const item of sources){const bytes=readFileSync(new URL(item.file,root));expect(createHash('sha256').update(bytes).digest('hex')).toBe(item.sha256);}for(const license of ['JetBrainsMono-OFL.txt','D2Coding-OFL.txt','NotoSansKR-OFL.txt'])expect(readFileSync(new URL(license,root),'utf8')).toContain('SIL OPEN FONT LICENSE');});
