import {test,expect} from 'bun:test';
import {OpenRigRuntime} from './runtime.ts';
function setup(){let occupant='session1',running=false,restores=0,receiptComplete=false,fresh=false;const runtime=new OpenRigRuntime({fetch:async(url)=>{
 if(url.endsWith('/launch-plan'))return Response.json({status:'plan',mode:'restore',rigId:'rig',mutated:false,snapshot:{id:'snap',kind:'manual',createdAt:'2026-10-09'},nodes:[{logicalId:'dev',occupantSessionId:occupant,intendedAction:fresh?'fresh-primed':'resume-original',freshRequired:fresh}]});
 if(url.endsWith('/nodes'))return Response.json([{nodeId:'node',logicalId:'dev',canonicalSessionName:'dev@rig',sessionStatus:running?'running':'stopped'}]);
 if(url.includes('/restore/status/'))return receiptComplete?Response.json({ok:true,rigId:'rig',attemptId:1,currentIntendedSetVerdict:'partially_restored',currentNodes:[{nodeId:'node',logicalId:'dev',status:'attention_required',error:'SECRET'}]}):Response.json({code:'attempt_incomplete'},{status:409});
 if(url.endsWith('/restore/snap')){restores++;return Response.json({ok:true,status:'started',rigId:'rig',attemptId:restores});}
 if(url.endsWith('/snapshots'))return Response.json({id:'new',rigId:'rig',kind:'manual',status:'complete',createdAt:'2026-10-09',data:{secret:'SECRET'}});
 throw new Error('unexpected');
 }});return {runtime,change:()=>{occupant='session2';},running:()=>{running=true;},fresh:()=>{fresh=true;},complete:()=>{receiptComplete=true;},restores:()=>restores};}
test('recovery stale occupant cannot restore',async()=>{const s=setup();const p=await s.runtime.recovery.plan('rig');s.change();await expect(s.runtime.recovery.restore(p.planId,'r')).rejects.toMatchObject({code:'recovery_plan_changed'});expect(s.restores()).toBe(0);});
test('recovery blocks running team and never silently starts fresh',async()=>{for(const change of ['running','fresh'] as const){const s=setup();s[change]();const p=await s.runtime.recovery.plan('rig');expect(p.canRestore).toBe(false);await expect(s.runtime.recovery.restore(p.planId,'r')).rejects.toMatchObject({code:'restore_preconditions_failed'});expect(s.restores()).toBe(0);}});
test('snapshot capture is explicit and projection excludes stored credentials',async()=>{const s=setup();s.running();const p=await s.runtime.recovery.plan('rig');const r=await s.runtime.recovery.snapshot(p.planId,'r');expect(r.id).toBe('new');expect(JSON.stringify(r)).not.toContain('SECRET');await expect(s.runtime.recovery.snapshot(p.planId,'r')).rejects.toMatchObject({code:'recovery_plan_expired'});});
test('restore started, running, and completed are separate states with truthful per-seat status',async()=>{const s=setup();const p=await s.runtime.recovery.plan('rig');expect((await s.runtime.recovery.restore(p.planId,'r')).status).toBe('started');expect((await s.runtime.recovery.status('rig',1)).status).toBe('running');const second=await s.runtime.recovery.plan('rig');await expect(s.runtime.recovery.restore(second.planId,'new')).rejects.toMatchObject({code:'restore_outcome_uncertain'});s.complete();const done=await s.runtime.recovery.status('rig',1);expect(done.status).toBe('completed');expect(done.nodes[0]?.status).toBe('attention_required');expect(JSON.stringify(done)).not.toContain('SECRET');});
