import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,writeFileSync,rmSync } from 'node:fs';import { join } from 'node:path';
import { chromium } from 'playwright-core';import { chromiumExecutable } from '../browser.ts';
import { activateRelease } from './activate.ts';import { rollbackRelease } from './rollback.ts';import { hash,files,type ReleaseManifest } from './manifest.ts';import { serveStatic } from '../../server/static.ts';
const root=mkdtempSync(join(process.env.TERMWEAVE_TEST_ROOT!,'release-browser-'));
function artifact(id:string){const directory=join(root,'releases',id);mkdirSync(join(directory,'dist','assets'),{recursive:true});writeFileSync(join(directory,'dist','index.html'),`<!doctype html><title>${id}</title><script>window.release='${id}'; window.loadOld=()=>import('/assets/${id}.js')</script>`);writeFileSync(join(directory,'dist','assets',id+'.js'),`export const version='${id}'`);const assets=files(join(directory,'dist'));const manifest:ReleaseManifest={schema:1,id,deployment:'frontend',source:{commit:'a'.repeat(40),tree:'b'.repeat(40),lock:hash('l'),upstreamLock:hash('u')},tools:{bun:Bun.version,node:process.version},native:{version:'fixture',checksum:hash('n')},compatibility:{backend:'1',storage:'v1-v3',protocol:'22'},tests:{status:'PASS',hash:hash('t')},assets,frontend:hash(JSON.stringify(Object.entries(assets).sort())),backend:hash('b')};writeFileSync(join(directory,'manifest.json'),JSON.stringify(manifest));}
artifact('A');artifact('B');await activateRelease(root,'A',async()=>true);
const server=Bun.serve({port:0,hostname:'127.0.0.1',fetch:request=>serveStatic(new URL(request.url).pathname,root)});
const browser=await chromium.launch({executablePath:chromiumExecutable(),headless:true});
try{const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.port}`);await page.evaluate(()=>{for(const version of ['v1','v2','v3'])localStorage.setItem('synthetic:'+version,JSON.stringify({version,ratio:.4}));});const before=await page.evaluate(()=>Object.entries(localStorage));await activateRelease(root,'B',async()=>true);assert.equal(await page.evaluate(async()=> (await (window as any).loadOld()).version),'A');await page.reload();assert.equal(await page.title(),'B');assert.deepEqual(await page.evaluate(()=>Object.entries(localStorage)),before);await rollbackRelease(root,async()=>true);await page.reload();assert.equal(await page.title(),'A');assert.deepEqual(await page.evaluate(()=>Object.entries(localStorage)),before);assert.equal((await page.request.get(`http://127.0.0.1:${server.port}/missing.js`)).status(),404);console.log('PASS old-client lazy import, A/B/A browser storage noninterference and missing asset 404');}finally{await browser.close();server.stop(true);rmSync(root,{recursive:true,force:true});}
