import { chromiumExecutable } from './browser.ts';
import './test-herdr.ts';
import assert from 'node:assert/strict';import { mkdtempSync,rmSync } from 'node:fs';import {tmpdir} from 'node:os';import{join}from'node:path';import{chromium}from'playwright-core';import{createServer}from'../server/index.ts';import{sessionSnapshot,workspaceCreate,workspaceClose}from'../server/herdr/client.ts';
const root=mkdtempSync(join(tmpdir(),'preview-app-owned-'));const own=await workspaceCreate({cwd:root,label:'preview-app-owned'});const server=createServer({port:0,hostname:'127.0.0.1',stateDir:root,token:''});const received:string[]=[];
const fixture=Bun.serve({port:0,hostname:'127.0.0.1',fetch(r){received.push(r.headers.get('cookie')??'');return new Response('<h1>Preview owned fixture</h1>',{headers:{'content-type':'text/html'}})}});
const browser=await chromium.launch({executablePath: chromiumExecutable(),headless:true});
try{const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'test-herdr-host-cookie',value:'owned-not-real-credential',domain:'127.0.0.1',path:'/'}]);const page=await context.newPage();const errors:string[]=[];const inputs:unknown[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('websocket',s=>s.on('framesent',f=>{try{const m=JSON.parse(String(f.payload));if(['input','keys'].includes(m.type))inputs.push(m)}catch{}}));
await page.goto(`http://127.0.0.1:${server.port}/?pane=${own.root_pane.pane_id}`);await page.locator('.conn-live').waitFor();const before=(await sessionSnapshot()).panes.find(p=>p.pane_id===own.root_pane.pane_id)!;
await page.getByRole('button',{name:'웹 미리보기 열기'}).click();const field=page.getByLabel('웹 주소',{exact:true});assert.ok(await field.evaluate(x=>x===document.activeElement));
await field.fill(`http://127.0.0.1:${fixture.port}/`);await field.press('Meta+Shift+ArrowDown');assert.ok(await field.evaluate(x=>x===document.activeElement));await field.press('Enter');assert.ok(await page.getByRole('button',{name:'제한된 내부 표시 시도'}).isDisabled());assert.equal(await page.locator('iframe').count(),0);assert.equal(received.length,0);assert.equal(inputs.length,0);
await field.focus();await field.press('Meta+l');assert.ok(await field.evaluate(x=>x===document.activeElement));await field.press('Escape');assert.equal(await page.locator('iframe').count(),0);
const after=(await sessionSnapshot()).panes.find(p=>p.pane_id===own.root_pane.pane_id)!;for(const k of ['terminal_id','cwd','workspace_id','tab_id'] as const)assert.equal(after[k],before[k]);assert.deepEqual(errors,[]);await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'웹 미리보기 열기'}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));console.log('PASS actualApp preview: samehost externalonly no iframe request/cookie; URL/MetaShiftArrow/MetaL/Escape zeroPTY; same terminal/cwd/layout, mobile nooverflow errors0');
}finally{await browser.close();server.stop();fixture.stop();await workspaceClose(own.workspace.workspace_id);rmSync(root,{recursive:true,force:true})}
