import { chromiumExecutable } from './browser.ts';
import './test-herdr.ts';import assert from'node:assert/strict';import{mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{chromium}from'playwright-core';import{createServer}from'../server/index.ts';import{workspaceCreate,workspaceClose,herdrRpc}from'../server/herdr/client.ts';
const root=mkdtempSync(join(tmpdir(),'spatial-owned-'));const own=await workspaceCreate({cwd:root,label:'spatial-owned'});const ids=[own.root_pane.pane_id];for(let i=0;i<3;i++)ids.push((await herdrRpc<any>('pane.split',{target_pane_id:ids[0],direction:'right',cwd:root,focus:false})).pane.pane_id);
const server=createServer({port:0,hostname:'127.0.0.1',stateDir:root,token:''});const browser=await chromium.launch({headless:true,executablePath: chromiumExecutable()});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.addInitScript(({w,ids})=>{localStorage.setItem('termweave:settings',JSON.stringify({language:'en',terminalInputMode:'direct'}));const g=(i:number)=>({kind:'group',id:`g${i}`,tabs:[ids[i]],active:ids[i]});const s=(id:string,axis:string,first:unknown,second:unknown,ratio:number)=>({kind:'split',id,axis,first,second,ratio});localStorage.setItem(`termweave:dock:v1:local:${w}`,JSON.stringify(s('c','columns',s('r1','rows',g(0),g(1),.6),s('r2','rows',g(2),g(3),.45),.58)));},{w:own.workspace.workspace_id,ids});const ready=new Set<string>();const frames:any[]=[];const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('websocket',s=>{s.on('framereceived',f=>{try{const m=JSON.parse(String(f.payload));if(m.type==='input-ready'&&m.ready!==false)ready.add(m.pane_id)}catch{}});s.on('framesent',f=>{try{const m=JSON.parse(String(f.payload));if(['input','keys'].includes(m.type))frames.push(m)}catch{}})});await page.goto(`http://127.0.0.1:${server.port}/?pane=${ids[0]}`);await page.locator('.conn-live').waitFor();await page.waitForFunction(()=>document.querySelectorAll('.xterm-helper-textarea').length===4);
const area=(i:number)=>page.locator(`[data-group-id="g${i}"] .xterm-helper-textarea`);await area(0).focus();
for(const[key,index]of [['Meta+ArrowRight',2],['Meta+Alt+ArrowDown',3],['Meta+ArrowLeft',1],['Meta+Alt+ArrowUp',0]] as const){await page.keyboard.press(key);await page.waitForFunction(id=>(document.activeElement as HTMLElement)?.closest('.dock-group')?.getAttribute('data-pane-id')===id,ids[index]);assert.ok(await area(index).evaluate(n=>n===document.activeElement));}
assert.equal(frames.length,0);await area(0).dispatchEvent('keydown',{key:'ArrowLeft',metaKey:true,bubbles:true,cancelable:true});assert.ok(await area(0).evaluate(n=>n===document.activeElement));assert.equal(frames.length,0);
assert.ok(await area(0).evaluate(n=>n===document.activeElement)); // IME matcher is separately exercised without leaving xterm in a synthetic composition.
await page.getByRole('button',{name:'Web preview Open'}).click();const url=page.getByLabel('Web address',{exact:true});await url.fill('https://example.com');await url.press('Meta+ArrowLeft');assert.ok(await url.evaluate(n=>n===document.activeElement));assert.equal(frames.length,0);await url.press('Escape');
await area(0).focus();const deadline=Date.now()+10000;while(!ready.has(ids[0]!)){assert.ok(Date.now()<deadline,'owned terminal input-ready timeout');await new Promise(resolve=>setTimeout(resolve,25));}await page.keyboard.press('a');await page.keyboard.press('ArrowLeft');const frameDeadline=Date.now()+5000;while(!frames.some(f=>f.pane_id===ids[0]&&f.text==='\u001b[D')){assert.ok(Date.now()<frameDeadline,'ordinary arrow frame timeout');await new Promise(resolve=>setTimeout(resolve,25));}assert.ok(frames.some(f=>f.text==='a'),'ordinary text preserved');const count=frames.length;await page.getByRole('button',{name:'Zoom',exact:true}).first().click();await page.locator('.xterm-helper-textarea').focus();await page.keyboard.press('Meta+ArrowRight');assert.equal(await page.locator('.dock-group').count(),1);assert.equal(frames.length,count);assert.deepEqual(errors,[]);console.log('PASS realApp spatial: all4directions actualfocus Cmdalias/CmdOption nestedunequal; boundary/IME/preview excluded zeroPTY; ordinaryarrow retained; zoomvisibleonly errors0');
}finally{await browser.close();server.stop();await workspaceClose(own.workspace.workspace_id);rmSync(root,{recursive:true,force:true})}
